spring:
  artemis:
    user: admin
    password: password
    broker-url: (tcp://localhost:61617,tcp://localhost:61717)?useTopologyForLoadBalancing=true&sslEnabled=true&trustStoreType=PKCS12&trustStorePath=truststore.p12&trustStorePassword=changeit&verifyHost=false&confirmationWindowSize=1048576&blockOnDurableSend=false&blockOnAcknowledge=false&consumerWindowSize=65536&reconnectAttempts=10&retryInterval=2000&retryIntervalMultiplier=1.5&maxRetryInterval=15000
    pool:
      enabled: true                 # enable JmsPoolConnectionFactory
      max-connections: 10           # max physical connections
      idle-timeout: 30000           # ms before idle connections are closed
      block-if-full: true           # block when max connections reached
      block-if-full-timeout: 5000   # ms to wait for a connection, -1 = forever

  # Listener/session behavior
  jms:
    listener:
      min-concurrency: 5            # min concurrent consumers
      max-concurrency: 10           # max concurrent consumers
      session:
        acknowledge-mode: auto      # auto, client, dups-ok
        transacted: false           # true = transacted session

    template:
      session:
        acknowledge-mode: auto      # auto, client, dups-ok
        transacted: false           # true = transactional send

  retry:
    max-attempts: 2                 # max retry attempts for sending messages
    delay: 1000                     # interval between retries in ms
    multiplier: 1.0                 # multiplier for increasing the interval
    max-delay: 10000                # max interval between retries in ms
        

app:
  queue:
    request: requestQueue
    sync: syncQueue
    transaction: transactionQueue

logging:
  level:
    root: info
    com.example.artemis: debug
    org.apache.activemq.artemis.jms.client: debug
    org.messaginghub.pooled.jms: debug