spring:
  artemis:
    user: admin
    password: password
    broker-url: (tcp://localhost:61617,tcp://localhost:61717)?sslEnabled=true&trustStoreType=PKCS12&trustStorePath=truststore.p12&trustStorePassword=changeit&verifyHost=false&confirmationWindowSize=0&blockOnDurableSend=true&blockOnAcknowledge=true
    ##useTopologyForLoadBalancing=true
    ##&reconnectAttempts=5&retryInterval=1000&retryIntervalMultiplier=1.0&maxRetryInterval=5000
    ##&consumerWindowSize=-1&producerWindowSize=-1
    ##&connectionTtl=60000
    
    pool:
      enabled: true                     # enable JmsPoolConnectionFactory
      max-connections: 2                # max physical connections
      max-sessions-per-connection: 20   # max sessions per connection
      idle-timeout: 30000               # ms before idle connections are closed
      block-if-full: true               # block when max connections reached
      block-if-full-timeout: 5000       # ms to wait for a connection, -1 = forever

  # Listener/template parameters
  jms:
    listener:
      min-concurrency: 2                # min concurrent consumers
      max-concurrency: 10               # max concurrent consumers
      session:
        acknowledge-mode: client        # session acknowledge mode

    template:
      receive-timeout: 1000             # timeout for receive() in ms
      session:
        acknowledge-mode: client        # session acknowledge mode

app:
  queue:
    sync: syncQueue

logging:
  level:
    root: info
    com.example.artemis: debug
    # org.apache.activemq.artemis: debug
    # org.apache.activemq.artemis.core.client: debug
    # org.apache.activemq.artemis.api.core.client: debug
    # org.apache.activemq.artemis.jms.client: debug
    # org.springframework.jms.connection: debug
    # org.springframework.jms.listener: debug    
    # org.messaginghub.pooled.jms: debug