server:
  port: 8080

spring:
  artemis:
    # Artemis broker connection
    # !!! Remove verifyHost=false for production use !!!
    broker-url: (tcp://localhost:61617,tcp://localhost:61717)?useTopologyForLoadBalancing=true&sslEnabled=true&trustStoreType=PKCS12&trustStorePath=truststore.p12&trustStorePassword=changeit&verifyHost=false
    user: admin
    password: password
    mode: native                           # default: "embedded" (switch to "native" if broker-url is set)

    pool:
      enabled: true                        # default false (pooling disabled by default)
      max-connections: 1                   # default 1
      max-sessions-per-connection: 500     # default 500
    
app:
  artemis:
    queues:
      - exampleQueue1
      - exampleQueue2
    confirmation-window-size: 1048576      # default -1 (disabled), required for async sends
    consumer:
      mode: SYNC                           # SYNC, ASYNC, REPLY, or TX
      threads-per-queue: 2

logging:
  level:
    root: info
    com.example.artemis: debug