spring:
  artemis:
    user: admin
    password: password
    broker-url: (tcp://localhost:61617,tcp://localhost:61717)?useTopologyForLoadBalancing=true&sslEnabled=true&trustStoreType=PKCS12&trustStorePath=truststore.p12&trustStorePassword=changeit&verifyHost=false&reconnectAttempts=1&failoverAttempts=1&retryInterval=100&clientFailureCheckPeriod=100
    #broker-url: tcp://localhost:61617?useTopologyForLoadBalancing=false
    #&connectionTTL=10&clientFailureCheckPeriod=10
    #&consumerWindowSize=0
    #&confirmationWindowSize=1048576
    ##&callTimeout=10000&blockOnAcknowledge=false
    ##&retryIntervalMultiplier=1.0&maxRetryInterval=5000
    ##&producerWindowSize=-1
    
    pool:
      enabled: true                     # enable JmsPoolConnectionFactory
      max-connections: 2                # max physical connections
      max-sessions-per-connection: 500  # max sessions per connection
      idle-timeout: 30000               # ms before idle connections are closed

  # Listener/template parameters
  jms:
    listener:
      min-concurrency: 1                # min concurrent consumers
      max-concurrency: 10                # max concurrent consumers
      session:
        acknowledge-mode: auto          # session ack mode
    

    # template:
    #   receive-timeout: 1000             # timeout for receive() in ms

app:
  queue:
    async: asyncQueue

logging:
  level:
    root: info
    com.example.artemis: debug
    org.apache.activemq.artemis: debug
    org.apache.activemq.artemis.core.client: debug
    org.apache.activemq.artemis.api.core.client: debug
    org.apache.activemq.artemis.jms.client: debug
    org.springframework.jms.connection: debug
    org.springframework.jms.listener: debug    
    org.messaginghub.pooled.jms: debug
