spring:
  artemis:
    user: admin
    password: password
    broker-url: (tcp://localhost:61617,tcp://localhost:61717)?sslEnabled=true&trustStoreType=PKCS12&trustStorePath=truststore.p12&trustStorePassword=changeit&verifyHost=false&reconnectAttempts=1&failoverAttempts=1&callTimeout=10000
    ##&useTopologyForLoadBalancing=false
    ##&retryInterval=1000&retryIntervalMultiplier=1.0&maxRetryInterval=5000
    ##&consumerWindowSize=-1&producerWindowSize=-1
    ##&confirmationWindowSize=1048576
    
    pool:
      enabled: true                     # enable JmsPoolConnectionFactory
      max-connections: 1                # max physical connections
      max-sessions-per-connection: 500  # max sessions per connection
      idle-timeout: 30000               # ms before idle connections are closed

  # Listener/template parameters
  jms:
    listener:
      min-concurrency: 2            # min concurrent consumers
      max-concurrency: 2            # max concurrent consumers

    template:
      receive-timeout: 1000         # timeout for receive() in ms


app:
  queue:
    async: asyncQueue
    request: requestQueue
    reply: replyQueue
    sync: syncQueue
    transaction: transactionQueue
  consumer:
    callback-url: http://localhost:8080/artemis/receive/transaction

logging:
  level:
    root: info
    com.example.artemis: debug
    # org.apache.activemq.artemis: debug
    # org.apache.activemq.artemis.core.client: debug
    # org.apache.activemq.artemis.api.core.client: debug
    # org.apache.activemq.artemis.jms.client: debug
    # org.springframework.jms.connection: debug
    # org.springframework.jms.listener: debug
    # org.springframework.jms: debug  
    # org.springframework.transaction: debug  
    # org.messaginghub.pooled.jms: debug
    # org.messaginghub.pooled.jms.JmsPoolConnection: debug
    # org.messaginghub.pooled.jms.JmsPoolSession: debug
    